### ISSUE TITLE
大佬 tg推送失败怎么回事

### ISSUE THREAD

**Issue by hanlihanshaobo** [ccwav/QLScript#1]
资产变动可以推送成功 ck检查推送报错 青龙
HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/ql/scripts/node_modules/.pnpm/got@11.8.2/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: undefined,

**Comment by ccwav** [comment]
客户端请求的语法错误，服务器无法理解
网络丢包导致的抽风吧

**Comment by ccwav** [comment]
信息太长导致，先Mark

**Comment by hanlihanshaobo** [comment]
> 信息太长导致，先Mark

那需要怎么设置

**Comment by ccwav** [comment]
> > 信息太长导致，先Mark
> 
> 那需要怎么设置

没那种设置，机器人问题，消息太长就报错，要改资产通知做数据分段发送通知，有空再看

**Comment by ccwav** [comment]
> > 信息太长导致，先Mark
> 
> 那需要怎么设置

已添加BEANCHANGE_PERSENT 变量拆分通知，请自行设定解决

**Comment by hanlihanshaobo** [comment]
> > > 信息太长导致，先马克
> > 
> > 
> > 那需要怎么设置
> 
> 已添加BEANCHANGE_PERSENT 拆分通知，请自行设置解决
辛苦了，我试试
