### ISSUE TITLE
关于京喜工厂推送频率比较高，能否设置限制次数

### ISSUE THREAD

**Issue by mjyhj** [ccwav/QLScript#10]
由于京喜工厂的频率推送特别高，如果不收获就频繁推送。
可否设置同一次收获，推送最多3次，3次后不再推送，直到重新选择才重置
3次后，只由资产变动白嫖那里提醒。

萌宠和农场同理

**Comment by ccwav** [comment]
我也想，不知道青龙有没办法给全局变量赋值，简单粗暴的方案是屏蔽掉😅

**Comment by mjyhj** [comment]
> 我也想，不知道青龙有没办法给全局变量赋值，简单粗暴的方案是屏蔽掉😅

那有没有可以办法可以设置，指定活动的pt_pin屏蔽推送

**Comment by ccwav** [comment]
这个可以有，想法不错

**Comment by ccwav** [comment]
突然想到，可以用别名缓存文件搞事情，有戏

**Comment by ccwav** [comment]
想想没必要，加个开关要么保留要么丢了，反正资产通知有

**Comment by mjyhj** [comment]
> 想想没必要，加个开关要么保留要么丢了，反正资产通知有。
> 
> 主要还是懒。。。。。

把NOTIFY_COMPTOGROUP2改成 用户自定义选择 哪些收获推过去群组2就可以了，也方便以后有其他新增的。

**Comment by ccwav** [comment]
> > 想想没必要，加个开关要么保留要么丢了，反正资产通知有。
> > 主要还是懒。。。。。
> 
> 把NOTIFY_COMPTOGROUP2改成 用户自定义选择 哪些收获推过去群组2就可以了，也方便以后有其他新增的。
> 这样就可以把工厂不推过去，只从资产那里推送工厂，其它同理

(5) NOTIFY_COMPTOGROUP2 和 NOTIFY_NOREMIND (待验证)

用法1 : export NOTIFY_COMPTOGROUP2="true"	

	    东东农场 东东萌宠 京喜工厂  这三个任务接收到产品可以兑换通知时推送到群组2.
		
用法2 : export NOTIFY_COMPTOGROUP2="东东农场&东东萌宠&京喜工厂"	

	    东东农场 东东萌宠 京喜工厂的兑换通知推送到群组2,可自行删减.		
		
用法3 : export NOTIFY_NOREMIND="东东农场&东东萌宠&京喜工厂"	

	    屏蔽东东农场 东东萌宠 京喜工厂的兑换通知,可自行删减.		

群组2的介绍:假如企业微信配置了QYWX_AM和QYWX_AM2,则发送兑换通知时会推送到QYWX_AM2配置的企业微信.

(PS:例子使用了企业微信的变量QYWX_AM,实际是所有推送变量后加2都会有效.)

**Comment by mjyhj** [comment]
export NOTIFY_COMPTOGROUP2="东东农场&东东萌宠"	            ##东东农场 东东萌宠 京喜工厂的兑换通知推送到群组2,可自行删减

我设置了这个，今天收菜，东东农场发送到 群组1去通知了，群组2并没有收到通知

**Comment by ccwav** [comment]
那得等我有水果可以收我才知道啥原因了。。。。

**Comment by mjyhj** [comment]
> 那得等我有水果可以收我才知道啥原因了。。。。

可能没有被判断到true那边去吧

**Comment by ccwav** [comment]
> export NOTIFY_COMPTOGROUP2="东东农场&东东萌宠"
> 
> 我设置了这个，今天收菜，东东农场发送到 群组1去通知了，群组2并没有收到通知

更新完试试

**Comment by yuzhilz** [comment]
> > > 想想没必要，加个开关要么保留要么丢了，反正资产通知有。
> 
> > > 主要还是懒。。。。。
> 
> > 
> 
> > 把NOTIFY_COMPTOGROUP2改成 用户自定义选择 哪些收获推过去群组2就可以了，也方便以后有其他新增的。
> 
> > 这样就可以把工厂不推过去，只从资产那里推送工厂，其它同理
> 
> 
> 
> (5) NOTIFY_COMPTOGROUP2 和 NOTIFY_NOREMIND (待验证)
> 
> 
> 
> 用法1 : export NOTIFY_COMPTOGROUP2="true"	
> 
> 
> 
> 	    东东农场 东东萌宠 京喜工厂  这三个任务接收到产品可以兑换通知时推送到群组2.
> 
> 		
> 
> 用法2 : export NOTIFY_COMPTOGROUP2="东东农场&东东萌宠&京喜工厂"	
> 
> 
> 
> 	    东东农场 东东萌宠 京喜工厂的兑换通知推送到群组2,可自行删减.		
> 
> 		
> 
> 用法3 : export NOTIFY_NOREMIND="东东农场&东东萌宠&京喜工厂"	
> 
> 
> 
> 	    屏蔽东东农场 东东萌宠 京喜工厂的兑换通知,可自行删减.		
> 
> 
> 
> 群组2的介绍:假如企业微信配置了QYWX_AM和QYWX_AM2,则发送兑换通知时会推送到QYWX_AM2配置的企业微信.
> 
> 
> 
> (PS:例子使用了企业微信的变量QYWX_AM,实际是所有推送变量后加2都会有效.)
> 
> 

用法2好像不行，农场兑换通知推到了群1,之前一直用法1可以推到群2

**Comment by mjyhj** [comment]
> > export NOTIFY_COMPTOGROUP2="东东农场&东东萌宠"
> > 我设置了这个，今天收菜，东东农场发送到 群组1去通知了，群组2并没有收到通知
> 
> 更新完试试

我把工厂去掉，现在正常了，工厂只推到群组1，群组2的资产变动也有显示工厂白嫖

**Comment by ccwav** [comment]
> > > > 想想没必要，加个开关要么保留要么丢了，反正资产通知有。
> > 
> > 
> > > > 主要还是懒。。。。。
> > 
> > 
> > > 
> > 
> > 
> > > 把NOTIFY_COMPTOGROUP2改成 用户自定义选择 哪些收获推过去群组2就可以了，也方便以后有其他新增的。
> > 
> > 
> > > 这样就可以把工厂不推过去，只从资产那里推送工厂，其它同理
> > 
> > 
> > (5) NOTIFY_COMPTOGROUP2 和 NOTIFY_NOREMIND (待验证)
> > 用法1 : export NOTIFY_COMPTOGROUP2="true"
> > ```
> >   东东农场 东东萌宠 京喜工厂  这三个任务接收到产品可以兑换通知时推送到群组2.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 用法2 : export NOTIFY_COMPTOGROUP2="东东农场&东东萌宠&京喜工厂"
> > ```
> >   东东农场 东东萌宠 京喜工厂的兑换通知推送到群组2,可自行删减.		
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 用法3 : export NOTIFY_NOREMIND="东东农场&东东萌宠&京喜工厂"
> > ```
> >   屏蔽东东农场 东东萌宠 京喜工厂的兑换通知,可自行删减.		
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 群组2的介绍:假如企业微信配置了QYWX_AM和QYWX_AM2,则发送兑换通知时会推送到QYWX_AM2配置的企业微信.
> > (PS:例子使用了企业微信的变量QYWX_AM,实际是所有推送变量后加2都会有效.)
> 
> 用法2好像不行，农场兑换通知推到了群1,之前一直用法1可以推到群2

我用export NOTIFY_COMPTOGROUP2="东东农场&东东萌宠" ，京喜工厂现在是推送到组1，农场跟萌宠得等我有东西成熟才能测试.

**Comment by ccwav** [comment]
找到问题了，测试中

**Comment by ccwav** [comment]
修复了
