### ISSUE TITLE
添加了多个推送渠道后，取消无效

### ISSUE THREAD

**Issue by mjyhj** [ccwav/QLScript#13]
之前设置了
TG1
TG2
PUSHPLUS1
PUSHPLUS2
后面新增了企业微信1和2后，把pushplus变量注释或者删掉后，pushplus仍然会推送

**Comment by ccwav** [comment]
除非是执行任务前就已经载入了内存，然后那个任务执行了很久才完成。
否则绝不可能

**Comment by mjyhj** [comment]
> 除非是执行任务前就已经载入了内存，然后那个任务执行了很久才完成。
> 否则绝不可能

我特意试了一下，还是这样，跑的资产变动

**Comment by ccwav** [comment]
又去看了一眼代码，确实逻辑是优先1，2没设置则用1

**Comment by mjyhj** [comment]
> 又去看了一眼代码，确实逻辑是优先1，2没设置则用1

貌似是青龙的问题，每次重启docker的时候，当前的环境变量会变成缺省值。

例如我当前已经设置了
PUSHPLUS1：AAA
PUSHPLUS2：BBB
然后重启docker，再把PUSHPLUS2：设置成空白，就生效
这时候如果把PUSHPLUS2注释掉
会恢复成重启前的缺省值PUSHPLUS2：BBB

https://raw.githubusercontent.com/JDHelloWorld/jd_scripts/main/jd_env_copy.js
用这个可以导出来看

**Comment by ccwav** [comment]
所以代码不能注释只能清空，有点6啊
