### ISSUE TITLE
京东ck检测报错

### ISSUE THREAD

**Issue by herunyu** [ccwav/QLScript#14]
可否帮忙看看是什么问题造成的？资产变动脚本能正常执行。

❗️京东CK检测, 错误!

👇👇👇👇👇检测出错账号👇👇👇👇👇
京东CK检测 :"Invalid character in header content [\"cookie\"]"

**Comment by ccwav** [comment]
注意到这个问题了，当环境变量存在其他值时候会有这个错误

**Comment by herunyu** [comment]
我之前每个cookie之间加了&和换行，现在去掉换行后也只能识别第一个账号，请问大佬这里对多cookies的格式有什么要求能说明一下吗，感谢！ @ccwav

**Comment by ccwav** [comment]
脚本只支持青龙环境😑

**Comment by herunyu** [comment]
我是青龙环境呀，其他的都能跑诶，包括你写的资产变动脚本也能所有cookies正常执行。。。
