### ISSUE TITLE
这种情况不知道是农场没种植还是没收菜导致没推送

### ISSUE THREAD

**Issue by mjyhj** [ccwav/QLScript#15]
资产变动：
******开始查询【京东账号5】龙王*********
👇=======账号5=======👇
【账号名称】安格斯龙王
【今日收支】收入127京豆
【昨日收支】收入85京豆
【当前京豆】606京豆(≈6.06元)
【极速金币】14890金币(≈1.49元)
【京东赚赚】43900金币(≈4.39元)
【京东秒杀】2866秒秒币(≈2.87元)
【领现金】1.99元
【东东农场】1kg虾稻米 可以兑换了!
【东东萌宠】3层抽纸巾30包(27%,2/4块)
🧧🧧🧧红包明细🧧🧧🧧
【当前总红包】12.51(总过期0.64)元 
【京喜红包】0.92(将过期0.00)元 
【极速红包】11.40(将过期0.58)元 
【京东红包】0.19(将过期0.06)元 
【健康红包】0.00(将过期0.00)元 

农场日志：
==============📣系统通知📣==============
东东农场
【京东账号5】 龙王
【提醒⏰】您忘了种植新的水果
请去京东APP或微信小程序选购并种植新的水果
点击弹窗即达
开始发送通知...
东东农场没有种植，不推送

这种情况，不清楚到底是忘记种植，还是没有去收菜。
资产变动和农场都没推送提示，建议把忘记种植也提取到 资产变动白嫖提醒里去

**Comment by ccwav** [comment]
忘了种植新的水果是永远不推送，然后我刚改完资产脚本加了任务提醒榜.
