### ISSUE TITLE
推送群组1跟群组2不是同一类的情况下

### ISSUE THREAD

**Issue by dddddtf** [ccwav/QLScript#18]
推送1设置了qywx，推送2设置了pp，NOTIFY_GROUP_LIST设置了还是只推送到企业微信，NOTIFY_COMPTOGROUP2的农场成熟就可以推送的pp

**Comment by ccwav** [comment]
并不存在这个问题，先确认你拿的是最新版本，且设定没有问题再说

**Comment by ccwav** [comment]
对了，还有一点，你的问题描述一点都不详细，根本无从查起。

**Comment by dddddtf** [comment]
![Screenshot_2021_0919_120459](https://user-images.githubusercontent.com/89177189/133915140-b31ca72c-49f3-488e-ae8c-240419742375.png)
![Screenshot_2021_0919_120432](https://user-images.githubusercontent.com/89177189/133915146-4a4b13b3-3896-469a-a089-9929d4bfb4d9.png)
NOTIFY_GROUP_LIST="京东CK检测&京东资产变动&Ninja 运行通知"
NOTIFY_COMPTOGROUP2="东东农场&东东萌宠&京喜工厂"
就是农场跟资产变动都通知变量分别是这样设置的，然后通知效果就像图上面那样，语言表达能力不太行，描述不出来了

**Comment by ccwav** [comment]
NOTIFY_GROUP_LIST 设置问题吧，好像并没有读取到

**Comment by dddddtf** [comment]
我在研究研究

**Comment by mjyhj** [comment]
如果推送2的渠道和推送1不同的话，渠道也要设置2个才可以
例如推送1
qywx=abc
推送2
pp=空白值即可
pp=xyz

**Comment by dddddtf** [comment]
> 如果要设置推送2，必须要推送1设置也要
> 例如
> 推送1
> qywx = ABC
> PP =值空白即可
> 推送2
> PP2 = XYZ
感谢，我试试

**Comment by ccwav** [comment]
> 如果要设置推送2，必须要推送1也要设置
> 例如
> 推送1
> qywx=abc
> pp=空白值即可
> 推送2
> pp2=xyz

1不是默认的吗，本来就有的啊-_-!!!
再者，这个优先取1的问题后面我修复了

**Comment by mjyhj** [comment]
> > 如果要设置推送2，必须要推送1也要设置
> > 例如
> > 推送1
> > qywx=abc
> > pp=空白值即可
> > 推送2
> > pp2=xyz
> 
> 1不是默认的吗，本来就有的啊-_-!!!
> 再者，这个优先取1的问题后面我修复了

酱紫，我以前没添加1，2会失效。一直留了一个1的空白值
