### ISSUE TITLE
BEANCHANGE_USERGP1和BEANCHANGE_USERGP2，分组后资产和白嫖的ID序号对不上

### ISSUE THREAD

**Issue by mjyhj** [ccwav/QLScript#23]
例子2 :  高级用法,需搭配发送通知脚本食用!

总共Test1~10 10个账号,变量设置如下:

export BEANCHANGE_USERGP1="test1&test2&test3&test4&test8"

export NOTIFY_CUSTOMNOTIFY=["京东资产变动#1&组2&企业微信应用消息","京东资产变动&组2&pushplus","京东白嫖榜#1&组2&企业微信应用消息","京东白嫖榜&组2&pushplus"] 

效果:通知会拆成2次进行发送:

	1) 通知标题为京东资产变动#1,内容为 test1 test2 test3 test4 test8 5个账号的资产,推送到组2的企业微信应用消息.
	
	   通知标题为京东白嫖榜#1,内容为 test1 test2 test3 test4 test8 5个账号的白嫖榜,推送到组2的企业微信应用消息.
		
	2) 通知标题为京东资产变动,内容为除了 test1 test2 test3 test4 test8 5个账号其他账号的资产,推送到组2的pushplus.
	
	   通知标题为京东白嫖榜,内容为除了 test1 test2 test3 test4 test8 5个账号其他账号的白嫖榜,推送到组2的pushplus.

```
这样资产变动的ID和CK的序号对不上，会这样显示
京东资产变动#1                                       京东资产变动
【账号1🆔】test1                                 【账号1🆔】test5
【账号2🆔】test2                                 【账号2🆔】test6
【账号3🆔】test3                                 【账号3🆔】test7
【账号4🆔】test4                                 【账号4🆔】test9
【账号5🆔】test8                                 【账号5🆔】test10

可否修改成这样：
京东资产变动#1                                       京东资产变动
【账号1🆔】test1                                 【账号5🆔】test5
【账号2🆔】test2                                 【账号6🆔】test6
【账号3🆔】test3                                 【账号7🆔】test7
【账号4🆔】test4                                 【账号9🆔】test9
【账号8🆔】test8                                 【账号10🆔】test10

```

京东白嫖榜的ID和CK序号是对得上的

**Comment by ccwav** [comment]
收到

**Comment by ccwav** [comment]
已修正

**Comment by mjyhj** [comment]
> 已修正

资产还是一样ID号和CK号对不上
白嫖提醒反而显示不到了

【⏰商品白嫖活动领取提醒⏰】
【账号undefined XX】牙线棒2盒 (京喜工厂)

**Comment by ccwav** [comment]
已修正
