### ISSUE TITLE
"getaddrinfo EAI_AGAIN cdn.jdsign.cf" 京东资产变动 getSign API请求失败，请检查网路重试

### ISSUE THREAD

**Issue by spiritLHL** [ccwav/QLScript#3]
![](http://imgpic.cn/2021/09/03/2021092b8191cc26d6b.png)
如题，报错如上图，IP地址在香港

**Comment by ccwav** [comment]
领现金要调用第三方库获取签名，不上传ck，这个是访问该第三方库网站出错导致，检查你的网络或将dns服务器改成114.114.114.114看是否能正常访问
