### ISSUE TITLE
用大佬的 sendNotify.js，如何实现只推送某几个 CK 的资产变化信息？

### ISSUE THREAD

**Issue by Deleted-Account** [ccwav/QLScript#5]
以前我是通过部署两个 dockers，其中一个只用来发送资产变化

看到大佬的 sendNotify.js 可以实现根据标题推送给 QYWX_AM2 跟 PUSH_PLUS_USER2，
但好像是根据标题来决定分类的，

有没有办法实现 jd_bean_change.js
对于 CK 1 2 3  发送给 QYWX_AM，
CK 4 5 6 发送给 QYWX_AM2 ？

**Comment by ccwav** [comment]
这个要改 jd_bean_change.js实现，等我完成sendNotify.js后试试

**Comment by wxjbb** [comment]
很期待这个功能，大佬太强了，有tg群组吗？

**Comment by ccwav** [comment]
> 很期待这个功能，大佬太强了，有tg群组吗？

别太期待，有点复杂，不一定改，当我想挑战自己的时候再说吧

**Comment by ccwav** [comment]
提上日程，working。。。。。。。

**Comment by ccwav** [comment]
例子2 :  高级用法,需搭配发送通知脚本食用!
总共Test1~10 10个账号,变量设置如下:
export BEANCHANGE_USERGP1="test1&test2&test3&test4&test8"
export NOTIFY_CUSTOMNOTIFY=["京东资产变动#1&组2&企业微信应用消息","京东资产变动&组2&pushplus","京东白嫖榜#1&组2&企业微信应用消息","京东白嫖榜&组2&pushplus"] 

效果:通知会拆成2次进行发送:

  1) 通知标题为京东资产变动#1,内容为 test1 test2 test3 test4 test8 5个账号的资产,推送到组2的企业微信应用消息.
     通知标题为京东白嫖榜#1,内容为 test1 test2 test3 test4 test8 5个账号的白嫖榜,推送到组2的企业微信应用消息.
   
  2) 通知标题为京东资产变动,内容为除了 test1 test2 test3 test4 test8 5个账号其他账号的资产,推送到组2的pushplus.
     通知标题为京东白嫖榜,内容为除了 test1 test2 test3 test4 test8 5个账号其他账号的白嫖榜,推送到组2的pushplus.

Done!

**Comment by wxjbb** [comment]
666，大佬牛逼
