### ISSUE TITLE
当nickname包含pt_pin的字符，备注推送替换有问题

### ISSUE THREAD

**Issue by mjyhj** [ccwav/QLScript#6]
cookie1： pt_pin=**tommy** nickname=**tommy**123 remark=汤姆; 输出： 汤姆123
cookie2： pt_pin=jd_d 123 nickname=123**tommy** remark=本; 输出： 123汤姆

另外，微信的推送标题也含 pt_pin或nickname，没有做remark处理

**Comment by ccwav** [comment]
你把ck的顺序调整下就可以了，把ck2放到ck1上面，这样就会先处理ck2的remark，那么ck1就不会有重复的字符了。

重点，处理顺序是按照ck顺序来的，处理方式是查找字符整体置换。

另外标题我确实没替换，后续我会加上

**Comment by ccwav** [comment]
标题替换已修正

**Comment by mjyhj** [comment]
> 标题替换已修正

标题替换好像无效

**Comment by ccwav** [comment]
> > 标题替换已修正
> 
> 标题替换好像无效

具体哪个脚本，我去看看，
正常来说text = text.replace(new RegExp(`${$.UserName}|${$.nickName}`, 'gm'), " "+$.Remark); 就已经替换了标题才对.

**Comment by mjyhj** [comment]
> > > 标题替换已修正
> > 
> > 
> > 标题替换好像无效
> 
> 具体哪个脚本，我去看看，
> 正常来说text = text.replace(new RegExp(`${$.UserName}|${$.nickName}`, 'gm'), " "+$.Remark); 就已经替换了标题才对.

https://raw.githubusercontent.com/JDHelloWorld/jd_scripts/main/jd_fruit.js

**Comment by ccwav** [comment]
> > > > 标题替换已修正
> > > 
> > > 
> > > 标题替换好像无效
> > 
> > 
> > 具体哪个脚本，我去看看，
> > 正常来说text = text.replace(new RegExp(`${$.UserName}|${$.nickName}`, 'gm'), " "+$.Remark); 就已经替换了标题才对.
> 
> https://raw.githubusercontent.com/JDHelloWorld/jd_scripts/main/jd_fruit.js
> 
> 另外还有个问题
> 京喜工厂既不是用pt_pin也不是用nickname，直接用微信名来发送的，不知道这个能不能替换成备注名

东东农场我没问题啊，什么通知标题有账号？给个样式我看看.

脚本获取不了微信名的吧。。。。。。肯定不能替换

**Comment by mjyhj** [comment]
![1](https://user-images.githubusercontent.com/22577418/132288748-a944c4cb-4947-4006-a123-5e94e38ae157.png)

**Comment by mjyhj** [comment]
不好意思，我最早之前用的是
ql repo https://github.com/ccwav/QLScript.git "jd_" "sendNotify.js" "ql.js"
但是我后来已经改成
ql repo https://github.com/ccwav/QLScript.git "jd_" "" "ql.js|sendNotify.js"

由于青龙2.9.1会回档，导致我恢复了，搞到没有更新到sendNotify.js
我再测试一下

**Comment by mjyhj** [comment]
export CKREMARK="false" #显示CK备注，false为不显示
export SHOWREMARKTYPE="1"    ##效果: 账号名称：代码玩家
export NOTIFY_SKIP_REMARK_LIST=""

这种情况CK检测下
自动禁用和失效下，不会做REMARK处理，只有有效的才会REMARK处理
![1](https://user-images.githubusercontent.com/22577418/132334628-a9e1a11c-0dd2-4fbd-922c-bfacfb3d9643.png)

**Comment by ccwav** [comment]
> export CKREMARK="false" #显示CK备注，false为不显示
> export SHOWREMARKTYPE="1" ##效果: 账号名称：代码玩家
> export NOTIFY_SKIP_REMARK_LIST=""
> 
> 这种情况CK检测下
> 自动禁用和失效下，不会做REMARK处理，只有有效的才会REMARK处理
> ![1](https://user-images.githubusercontent.com/22577418/132334628-a9e1a11c-0dd2-4fbd-922c-bfacfb3d9643.png)

Fixed.

**Comment by ccwav** [comment]
测试完记得告诉我哈

**Comment by mjyhj** [comment]
> 测试完记得告诉我哈

正常了
