### ISSUE TITLE
大佬通知能否解决一下？Bark的

### ISSUE THREAD

**Issue by linyali888** [ccwav/QLScript#7]
Bark APP发送通知调用API失败！！
HTTPError: Response code 431 (Request Header Fields Too Large)
    at Request.<anonymous> (/ql/scripts/node_modules/.pnpm/got@11.8.2/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: undefined,
  timings: {
    start: 1630895001142,
    socket: 1630895001143,
    lookup: 1630895001161,
    connect: 1630895001162,
    secureConnect: 1630895001570,
    upload: 1630895001571,
    response: 1630895001646,
    end: 1630895001647,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 18,
      tcp: 1,
      tls: 408,
      request: 1,
      firstByte: 75,
      download: 1,
      total: 505
    }
  }
}

**Comment by ccwav** [comment]
是资产通知吗，文本太长导致的，使用变量分下段就可以了，详细看库说明。

**Comment by linyali888** [comment]
嗯可以了。。我就3个帐号怎么也要分段来弄

**Comment by linyali888** [comment]
Bark的原因是吗
