### ISSUE TITLE
京东资产变动推送TG失败

### ISSUE THREAD

**Issue by gnowmil** [ccwav/QLScript#8]
其它脚本推送正常，京东资产变动推送提示以下错误。
telegram发送通知消息失败！！

HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/ql/scripts/node_modules/.pnpm/got@11.8.2/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: undefined,
  timings: {
    start: 1630918965042,
    socket: 1630918965042,
    lookup: 1630918965045,
    connect: 1630918965047,
    secureConnect: 1630918965762,
    upload: 1630918965762,
    response: 1630918966272,
    end: 1630918966273,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 3,
      tcp: 2,
      tls: 715,
      request: 0,
      firstByte: 510,
      download: 1,
      total: 1231
    }
  }
}

**Comment by ccwav** [comment]
消息太长导致的，自己设置变量拆分帐号即可。
